//Листинг А.5
//Заголовочный файл keys.h

#ifndef _KEYS_H_
#define _KEYS_H_

#define 	F1		0x3B00
#define 	F2		0x3C00
#define 	F3		0x3D00
#define 	F4		0x3E00
#define 	F5		0x3F00
#define 	F6		0x4000
#define 	F7		0x4100
#define 	F8		0x4200
#define 	F9		0x4300
#define 	F10		0x4400


#define		HOME		0x4700
#define		UP		0x4800
#define		PGUP		0x4900
#define		LEFT		0x4B00
#define		RIGHT		0x4D00
#define		END		0x4F00
#define		DOWN		0x5000
#define		PGDN		0x5100
#define		INS		0x5200
#define		DEL		0x5300

#define		ENTER		0x1C0D
#define		TAB		0x0F09
#define		ESC		0x011B
#define		BS		0x0E08
#define	      	BELL	      	7

#endif